server:
  port: 8081
  tomcat:
    threads:
      max: 50 #允许最大线程数
    accept-count: 50 #最大排队等待数量
    max-connections: 100 #允许的最大连接
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true  #开启feign对sentinel的支持
hm:
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller
  db:
    database: hm-item
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123